# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "7a47f99e2700e6f96d81cdc1377497f3c144e454ba0e2eaa11d3891e733085c4"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_darwin_amd64.tar.gz",
        verified: "downloads.contextbridge.ai/cli/"
    end
    on_arm do
      sha256 "4f06d3fb78245871e234d3f72dac3b25dbd450f8698c3c91cc06dd412bd186fa"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_darwin_arm64.tar.gz",
        verified: "downloads.contextbridge.ai/cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "ca02f3b492a498161ab873eb4c449695e6bead7eb7ec44a7ba64e2763a0d9450"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_linux_amd64.tar.gz",
        verified: "downloads.contextbridge.ai/cli/"
    end
    on_arm do
      sha256 "fe9ef6cb96ada3fcdbca7cb530c12d252c1c1660179f0a8019410af85b399883"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_linux_arm64.tar.gz",
        verified: "downloads.contextbridge.ai/cli/"
    end
  end

  name "cli"
  desc "ContextBridge CLI — human-in-the-loop annotation for AI coding sessions"
  homepage "https://plan.contextbridge.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "contextbridge"

  # No zap stanza required

  caveats <<~EOS
    ContextBridge does its real work by hooking into your AI coding harnesses.
    Run this once to detect the harnesses on your machine and configure them:

        contextbridge install

    Docs: https://plan.contextbridge.ai
  EOS
end
