# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli" do
  version "0.7.2"

  on_macos do
    on_intel do
      sha256 "e244ea8471147e27b9c3e0c6fc33411c0cd36ffb73f1a0f4631ec513b259016f"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_darwin_amd64.tar.gz",
        verified: "downloads.contextbridge.ai/cli/"
    end
    on_arm do
      sha256 "5f17eecbbe00074fb269f0750808a970fd3eb03673bb777a8eb0bd223a7251b0"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_darwin_arm64.tar.gz",
        verified: "downloads.contextbridge.ai/cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "35c01fd546d12216386124b88adde084b66f856ae305413b3c08cea56a72d5e4"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_linux_amd64.tar.gz",
        verified: "downloads.contextbridge.ai/cli/"
    end
    on_arm do
      sha256 "81e9e449a75852cf238e8da62d57c80660d342bd9a6bb1092f77f9b8ae2da5ea"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_linux_arm64.tar.gz",
        verified: "downloads.contextbridge.ai/cli/"
    end
  end

  name "cli"
  desc "ContextBridge CLI — human-in-the-loop annotation for AI coding sessions"
  homepage "https://plan.contextbridge.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "contextbridge"

  # No zap stanza required

  caveats <<~EOS
    ContextBridge does its real work by hooking into your AI coding harnesses.
    Run this once to detect the harnesses on your machine and configure them:

        contextbridge install

    Docs: https://plan.contextbridge.ai
  EOS
end
