# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "3e136d270a1f986d812d6bb13956a2cd1b1ddb4fd63514733c30f872490d9c10"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_darwin_amd64.tar.gz",
        verified: "downloads.contextbridge.ai/cli/"
    end
    on_arm do
      sha256 "4fea22a8191c9009e79a936cc9057550643395e7d06ec10e7f185e855e95feea"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_darwin_arm64.tar.gz",
        verified: "downloads.contextbridge.ai/cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "4e9acaa1c1d1b8e922455a8c913ff4bc12b57491169f4abc1dd971fc3a1d6b03"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_linux_amd64.tar.gz",
        verified: "downloads.contextbridge.ai/cli/"
    end
    on_arm do
      sha256 "0206301a37e3111a7ced86e4354d86168c7751b5e6c786ea55ce2eea028ad1cc"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_linux_arm64.tar.gz",
        verified: "downloads.contextbridge.ai/cli/"
    end
  end

  name "cli"
  desc "ContextBridge CLI — human-in-the-loop annotation for AI coding sessions"
  homepage "https://plan.contextbridge.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "contextbridge"

  # No zap stanza required

  caveats <<~EOS
    ContextBridge does its real work by hooking into your AI coding harnesses.
    Run this once to detect the harnesses on your machine and configure them:

        contextbridge install

    Docs: https://plan.contextbridge.ai
  EOS
end
