# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@alpha" do
  version "0.11.2-alpha.1"

  on_macos do
    on_arm do
      sha256 "1029c607440f10a673119c6dfc3b05f1561f1655f6658af461909e8c744fd5bc"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "905a17174c322d208c97b1fef0f0fc70a051596158987e31352695bc0970ba90"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "05ffb812bae4fec9c2cfe9b21ad8918514fd77e2b9c006e11e9714b4c583e331"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a23c615355ed8e15ef0df74836cdabd51bfe77836340025042532fa41b11ee4c"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cli@alpha"
  desc "ContextBridge CLI (alpha channel) — human-in-the-loop annotation for AI coding sessions"
  homepage "https://plan.contextbridge.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "contextbridge"

  # No zap stanza required

  caveats <<~EOS
    ContextBridge does its real work by hooking into your AI coding harnesses.
    Run this once to detect the harnesses on your machine and configure them:

        contextbridge install

    Docs: https://plan.contextbridge.ai
  EOS
end
