# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@alpha" do
  version "0.3.0-alpha.2"

  on_macos do
    on_intel do
      sha256 "17b438bf7d1e00dd3b7989a4aa8a162830664bf9f0b9e86fca05a9713fa36556"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_darwin_amd64.tar.gz",
        verified: "downloads.contextbridge.ai/cli/"
    end
    on_arm do
      sha256 "74a4ab656149e9718e100e82d2b8edbe8387399fb85889475a6aef09ad175947"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_darwin_arm64.tar.gz",
        verified: "downloads.contextbridge.ai/cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "83fe1e04180fcc6cc4421571995bc166a5b76c451beb9f30aa9cc86d8ec371ee"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_linux_amd64.tar.gz",
        verified: "downloads.contextbridge.ai/cli/"
    end
    on_arm do
      sha256 "f2cf4ce0667d3b233132660c4eec4bc3f7b786196a378ff2c297fdbd74d7b2f4"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_linux_arm64.tar.gz",
        verified: "downloads.contextbridge.ai/cli/"
    end
  end

  name "cli@alpha"
  desc "ContextBridge CLI (alpha channel) — human-in-the-loop annotation for AI coding sessions"
  homepage "https://plan.contextbridge.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "contextbridge"

  # No zap stanza required

  caveats <<~EOS
    ContextBridge does its real work by hooking into your AI coding harnesses.
    Run this once to detect the harnesses on your machine and configure them:

        contextbridge install

    Docs: https://plan.contextbridge.ai
  EOS
end
