# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli@alpha" do
  version "0.8.0-alpha.0"

  on_macos do
    on_intel do
      sha256 "a3bed90765a58eaedece50b47ce7011d0b7a02dd276b0e78ab23bf0b54061f5e"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_darwin_amd64.tar.gz",
        verified: "downloads.contextbridge.ai/cli/"
    end
    on_arm do
      sha256 "df6a8fc3c8b01cf25fa421bec4a883b88765848fbd2c52b07d4d17e9e9254cae"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_darwin_arm64.tar.gz",
        verified: "downloads.contextbridge.ai/cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "7617e25994248185ce2d18436925feee66c60a3eff109a71c382485b4e496bfd"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_linux_amd64.tar.gz",
        verified: "downloads.contextbridge.ai/cli/"
    end
    on_arm do
      sha256 "5774d27d2d006e82ccaa68a3519b08d5e7db028a045067265f386072c9963f02"
      url "https://downloads.contextbridge.ai/cli/#{version}/contextbridge_#{version}_linux_arm64.tar.gz",
        verified: "downloads.contextbridge.ai/cli/"
    end
  end

  name "cli@alpha"
  desc "ContextBridge CLI (alpha channel) — human-in-the-loop annotation for AI coding sessions"
  homepage "https://plan.contextbridge.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "contextbridge"

  # No zap stanza required

  caveats <<~EOS
    ContextBridge does its real work by hooking into your AI coding harnesses.
    Run this once to detect the harnesses on your machine and configure them:

        contextbridge install

    Docs: https://plan.contextbridge.ai
  EOS
end
